import type { Metadata } from 'next';
import { NuqsAdapter } from 'nuqs/adapters/next/app';

import { Providers } from './providers';

import './globals.css';

import { auth } from '@/auth';
import Sonner from '@/components/providers';
import Navbar from '@/components/sections/navbar';
import { ThemeProvider } from '@/components/theme-provider';

export const metadata: Metadata = {
  title: 'The Polyclinic',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();

  return (
    <html lang="en" suppressHydrationWarning className="light">
      <body className="no-scrollbar">
        <Providers>
          <NuqsAdapter>
            <ThemeProvider attribute="class" defaultTheme="light">
              {/* <Nav session={session} /> */}
              <Navbar session={session} />
              {children}
              <Sonner />
            </ThemeProvider>
          </NuqsAdapter>
        </Providers>
      </body>
    </html>
  );
}
