name: Deploy to VPS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'pnpm'

      # Install pnpm
      - name: Install pnpm
        run: npm install -g pnpm

      # Install dependencies
      - name: Install dependencies
        run: pnpm install

      # Build the Next.js app
      - name: Build
        run: pnpm build

      # Deploy to VPS
      - name: Deploy to VPS
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          VPS_HOST: ${{ secrets.VPS_HOST }}
          VPS_USER: ${{ secrets.VPS_USER }}
          VPS_DEPLOY_PATH: ${{ secrets.VPS_DEPLOY_PATH }}
        run: |
          # Set up SSH
          echo "$SSH_PRIVATE_KEY" > private_key
          chmod 600 private_key
          eval $(ssh-agent -s)
          ssh-add private_key

          # Deploy to VPS
          ssh -o StrictHostKeyChecking=no $VPS_USER@$VPS_HOST << 'EOF'
            cd $VPS_DEPLOY_PATH
            git pull origin master
            pnpm install
            pnpm build
            pm2 restart the-polyclinic
          EOF

          # Clean up
          rm private_key
